#######################################################

# toolchain
# Use Windows default location (which returns Unix paths that don't work with mingw32-make)
CC := C:/Program Files/SDCC/bin/sdcc.exe
OBJCOPY := C:/Program Files/SDCC/bin/sdobjcopy.exe
PACK_HEX := C:/Program Files/SDCC/bin/packihx.exe
WCHISP ?= wchisptool -g -f

#######################################################

FREQ_SYS ?= 24000000

XRAM_SIZE ?= 0x0400

XRAM_LOC ?= 0x0000

CODE_SIZE ?= 0x3800

ROOT_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

# Build directory
BUILD_DIR := $(ROOT_DIR)build

CFLAGS := -V -mmcs51 --model-small \
	--xram-size $(XRAM_SIZE) --xram-loc $(XRAM_LOC) \
	--code-size $(CODE_SIZE) \
	-I$(ROOT_DIR)include -DFREQ_SYS=$(FREQ_SYS) \
	$(EXTRA_FLAGS)

LFLAGS := $(CFLAGS)

RELS := $(C_FILES:.c=.rel)

print-%  : ; @echo $* = $($*)

# Create build directory if it doesn't exist
$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

%.rel : %.c | $(BUILD_DIR)
	$(CC) -c $(CFLAGS) $< -o $(BUILD_DIR)/$(notdir $@)

# Note: SDCC will dump all of the temporary files into this one, so strip the paths from RELS
# For now, get around this by stripping the paths off of the RELS list.

$(BUILD_DIR)/$(TARGET).ihx: $(RELS) | $(BUILD_DIR)
	cd "$(BUILD_DIR)" && "$(CC)" $(notdir $(RELS)) $(LFLAGS) -o $(TARGET).ihx

$(BUILD_DIR)/$(TARGET).hex: $(BUILD_DIR)/$(TARGET).ihx
	"$(PACK_HEX)" $(BUILD_DIR)/$(TARGET).ihx > $(BUILD_DIR)/$(TARGET).hex

$(BUILD_DIR)/$(TARGET).bin: $(BUILD_DIR)/$(TARGET).ihx
	$(OBJCOPY) -I ihex -O binary $(BUILD_DIR)/$(TARGET).ihx $(BUILD_DIR)/$(TARGET).bin
	
flash: $(BUILD_DIR)/$(TARGET).bin pre-flash
	$(WCHISP) $(BUILD_DIR)/$(TARGET).bin

.DEFAULT_GOAL := all
all: $(BUILD_DIR)/$(TARGET).bin $(BUILD_DIR)/$(TARGET).hex

clean:
	rm -rf $(BUILD_DIR)
